### ISSUE TITLE
AVG Antivirus interrupts the session of KMC.

### ISSUE THREAD

**Issue by ColinRafaelPerez08** [KeppySoftware/KMC#58]
Apparently while using the KMC, AVG identified it as a virus called: IDP.Generic Should i be Worried Whatsoever? I'm Currently using the latest pre-release version of Keppy's MIDI Converter. An image of AVG's Warning can be seen below:
![image](https://user-images.githubusercontent.com/44690814/50966751-ef4d6e80-1510-11e9-916d-01e5117b3c7d.png)

**Comment by KaleidonKep99** [comment]
It's a false positive.
