### ISSUE TITLE
Note count which stored in "signed int"

### ISSUE THREAD

**Issue by DixelU** [KeppySoftware/KMC#59]
Actually that's not a bug, but more like a suggestion. 
There's some proofs.
![image](https://user-images.githubusercontent.com/26818917/51085719-23b66a00-175f-11e9-8f58-88c55b547ffb.png)
![image](https://user-images.githubusercontent.com/26818917/51085725-2f099580-175f-11e9-8727-8bf33265d192.png)

**Comment by KaleidonKep99** [comment]
The note count is stored as an UInt64 in KMC.

**Comment by DixelU** [comment]
Just read some sources and it really stored in (at least) as Int64. Is it possible that problem is in BASS library itself?

**Comment by KaleidonKep99** [comment]
BASS_MIDI_StreamGetEvents returns an UInt32, so that might be the issue.
I'll ask Ian Luck if he can make it return an UInt64 instead.

**Comment by KaleidonKep99** [comment]
Fixed.
